name = "forgex-cli"
version = "3.4.0"
license = "MIT"
author = "Amasaki Shinobu"
maintainer = "amasaki203@gmail.com"
copyright = "Copyright 2023-2024, Amasaki Shinobu"
homepage = "https://github.com/shinobuamasaki/forgex-cli"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
forgex = { git = "https://github.com/ShinobuAmasaki/forgex", branch = "exp"}
[preprocess]
[preprocess.cpp]
suffixes = ["f90", "F90"]